name: gazebo-kyrofa
version: 8.0.0
grade: stable
confinement: strict
summary: Robot simulation made easy
description: |
  Robot simulation is an essential tool in every roboticist's toolbox. A
  well-designed simulator makes it possible to rapidly test algorithms, design
  robots, perform regression testing, and train AI system using realistic
  scenarios. Gazebo offers the ability to accurately and efficiently simulate
  populations of robots in complex indoor and outdoor environments. At your
  fingertips is a robust physics engine, high-quality graphics, and convenient
  programmatic and graphical interfaces. Best of all, Gazebo is free with a
  vibrant community.

parts:
#  gazebo:
#    plugin: cmake
#    source: http://osrf-distributions.s3.amazonaws.com/gazebo/releases/gazebo-8.0.0.tar.bz2

  ignition-math:
    plugin: cmake
    source: https://bitbucket.org/ignitionrobotics/ign-math
    source-type: hg
    source-branch: ign-math3

    configflags: [-DCMAKE_INSTALL_PREFIX=/ignition-math]
    build-packages: [gcc, g++, sed]

  sdformat:
    plugin: cmake
    source: http://osrf-distributions.s3.amazonaws.com/sdformat/releases/sdformat-4.0.0.tar.bz2
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/
      - -DIGNITION-MATH_INCLUDE_DIRS=$SNAPCRAFT_STAGE/ignition-math/include/ignition/math3
      - -DIGNITION-MATH_LIBRARY_DIRS=$SNAPCRAFT_STAGE/ignition-math/lib
      - -DIGNITION-MATH_LIBRARIES=ignition-math3

    build-packages:
      - python
      - python-psutil
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-iostreams-dev
      - libtinyxml-dev
      - libxml2-utils
      - ruby-dev
      - ruby
    after: [ignition-math]

  ignition-messages:
    plugin: cmake
    source: https://bitbucket.org/ignitionrobotics/ign-msgs
    source-type: hg
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/ignition-messages
      - -DIGNITION-MATH_INCLUDE_DIRS=$SNAPCRAFT_STAGE/ignition-math/include/ignition/math3
      - -DIGNITION-MATH_LIBRARY_DIRS=$SNAPCRAFT_STAGE/ignition-math/lib
      - -DIGNITION-MATH_LIBRARIES=ignition-math3

    build-packages: [libprotoc-dev, libprotobuf-dev, protobuf-compiler]
    after: [ignition-math]

#  ignition-transport:
#    plugin: cmake
#    source: https://bitbucket.org/ignitionrobotics/ign-transport
#    source-type: hg
#    configflags:
#      - -Dignition-math4_DIR="$SNAPCRAFT_STAGE/ignition-math/lib/cmake/ignition-math3"
#
#    build-packages:
#      - pkg-config
#      - python
#      - ruby-ronn
#      - libprotoc-dev
#      - libprotobuf-dev
#      - protobuf-compiler
#      - uuid-dev
#      - libzmq3-dev
#    after: [ignition-messages, ignition-math]
